with mission_seed (
  id,
  slug,
  day_number,
  week_number,
  level,
  track,
  title,
  goal,
  scenario,
  estimated_minutes,
  target_chunks,
  target_vocabulary,
  practice_questions,
  roleplay_prompt
) as (
  values
    (
      '00000000-0000-4000-8000-000000000008'::uuid,
      'workplace-day-08-small-talk-opener',
      8,
      2,
      'A2',
      'workplace',
      'Start small talk',
      'Start a short workplace small-talk exchange and ask one friendly follow-up.',
      'You meet a colleague before a meeting starts.',
      20,
      '[{"text":"How is your day going?","meaningVi":"hom nay cua ban the nao","example":"How is your day going so far?"},{"text":"Did you get a chance to...?","meaningVi":"ban da co dip... chua","example":"Did you get a chance to review the design?"},{"text":"That sounds...","meaningVi":"nghe co ve...","example":"That sounds useful for the team."}]'::jsonb,
      '[{"word":"chance","meaningVi":"co hoi, dip","example":"Did you get a chance to check it?"},{"word":"quick","meaningVi":"nhanh","example":"Can we have a quick chat?"},{"word":"busy","meaningVi":"ban","example":"It has been a busy morning."}]'::jsonb,
      '["How can you start small talk before a meeting?","What follow-up question can you ask?","How do you respond to a colleague''s update?"]'::jsonb,
      'Act as a colleague waiting for a meeting. Let the learner start small talk and ask one follow-up question.'
    ),
    (
      '00000000-0000-4000-8000-000000000009'::uuid,
      'workplace-day-09-share-a-status-update',
      9,
      2,
      'A2',
      'workplace',
      'Share a status update',
      'Give a short update about what is done, in progress, and next.',
      'Your teammate asks for a quick project status.',
      20,
      '[{"text":"So far, I have...","meaningVi":"cho den hien tai toi da...","example":"So far, I have finished the login screen."},{"text":"I''m currently working on...","meaningVi":"hien tai toi dang lam...","example":"I''m currently working on the API connection."},{"text":"Next, I will...","meaningVi":"tiep theo toi se...","example":"Next, I will test the error states."}]'::jsonb,
      '[{"word":"status","meaningVi":"trang thai","example":"Here is the current status."},{"word":"in progress","meaningVi":"dang tien hanh","example":"The task is still in progress."},{"word":"next","meaningVi":"tiep theo","example":"Next, I will update the docs."}]'::jsonb,
      '["What have you finished so far?","What are you currently working on?","What will you do next?"]'::jsonb,
      'Act as a teammate asking for a quick status update. Ask what is done, what is in progress, and what is next.'
    ),
    (
      '00000000-0000-4000-8000-000000000010'::uuid,
      'workplace-day-10-describe-progress',
      10,
      2,
      'A2',
      'workplace',
      'Describe progress',
      'Explain progress with simple numbers, blockers, and confidence level.',
      'Your team lead asks how close your task is to completion.',
      20,
      '[{"text":"I''m about... percent done.","meaningVi":"toi da hoan thanh khoang... phan tram","example":"I''m about seventy percent done."},{"text":"The remaining part is...","meaningVi":"phan con lai la...","example":"The remaining part is testing the retry flow."},{"text":"I feel confident because...","meaningVi":"toi thay tu tin vi...","example":"I feel confident because the main feature is working."}]'::jsonb,
      '[{"word":"remaining","meaningVi":"con lai","example":"The remaining work is small."},{"word":"estimate","meaningVi":"uoc tinh","example":"My estimate is two hours."},{"word":"confident","meaningVi":"tu tin","example":"I am confident about this timeline."}]'::jsonb,
      '["How much progress have you made?","What is the remaining part?","How confident are you about the timeline?"]'::jsonb,
      'Act as a team lead asking for progress. Ask about percentage done, remaining work, and confidence.'
    ),
    (
      '00000000-0000-4000-8000-000000000011'::uuid,
      'workplace-day-11-ask-for-help',
      11,
      2,
      'A2',
      'workplace',
      'Ask for help',
      'Ask for help clearly without sounding passive or vague.',
      'You need help from a teammate to unblock your task.',
      20,
      '[{"text":"Could you help me with...?","meaningVi":"ban co the giup toi ve... khong","example":"Could you help me with the test data?"},{"text":"I''m not sure how to...","meaningVi":"toi chua chac cach...","example":"I''m not sure how to reproduce this issue."},{"text":"It would help if...","meaningVi":"se huu ich neu...","example":"It would help if you could share an example request."}]'::jsonb,
      '[{"word":"unblock","meaningVi":"go chan, thao go","example":"This will unblock my task."},{"word":"example","meaningVi":"vi du","example":"Can you share an example?"},{"word":"request","meaningVi":"yeu cau","example":"The request is missing a field."}]'::jsonb,
      '["What help do you need?","What are you not sure how to do?","What would help you move forward?"]'::jsonb,
      'Act as a teammate. Let the learner ask for help, then ask one follow-up about what they already tried.'
    ),
    (
      '00000000-0000-4000-8000-000000000012'::uuid,
      'workplace-day-12-answer-follow-up-questions',
      12,
      2,
      'A2',
      'workplace',
      'Answer follow-up questions',
      'Answer a follow-up question with context, detail, and a short check-back.',
      'A teammate asks follow-up questions after your update.',
      20,
      '[{"text":"The reason is...","meaningVi":"ly do la...","example":"The reason is that the API changed."},{"text":"For example...","meaningVi":"vi du...","example":"For example, the mobile layout breaks on small screens."},{"text":"Does that answer your question?","meaningVi":"dieu do co tra loi cau hoi cua ban khong","example":"Does that answer your question?"}]'::jsonb,
      '[{"word":"context","meaningVi":"boi canh","example":"Let me give some context."},{"word":"detail","meaningVi":"chi tiet","example":"Can you add one detail?"},{"word":"follow-up","meaningVi":"cau hoi tiep theo","example":"I have one follow-up question."}]'::jsonb,
      '["How do you explain the reason?","What example can you give?","How do you check if your answer is clear?"]'::jsonb,
      'Act as a teammate asking follow-up questions. Ask why, ask for an example, and let the learner check understanding.'
    ),
    (
      '00000000-0000-4000-8000-000000000013'::uuid,
      'workplace-day-13-summarize-a-meeting',
      13,
      2,
      'A2',
      'workplace',
      'Summarize a meeting',
      'Summarize a short meeting with decisions and next steps.',
      'A colleague missed a meeting and asks what happened.',
      25,
      '[{"text":"The main point was...","meaningVi":"y chinh la...","example":"The main point was that we should simplify the first release."},{"text":"We decided to...","meaningVi":"chung toi da quyet dinh...","example":"We decided to move the deadline to Friday."},{"text":"The next step is...","meaningVi":"buoc tiep theo la...","example":"The next step is to update the task list."}]'::jsonb,
      '[{"word":"decision","meaningVi":"quyet dinh","example":"The decision is final."},{"word":"action item","meaningVi":"viec can lam","example":"I have one action item."},{"word":"deadline","meaningVi":"han chot","example":"The deadline is Friday."}]'::jsonb,
      '["What was the main point?","What did the team decide?","What is the next step?"]'::jsonb,
      'Act as a colleague who missed the meeting. Ask the learner to summarize the main point, decision, and next step.'
    ),
    (
      '00000000-0000-4000-8000-000000000014'::uuid,
      'workplace-day-14-week-2-review',
      14,
      2,
      'A2',
      'workplace',
      'Week 2 interaction review',
      'Review workplace interaction skills from small talk to meeting summary.',
      'Your speaking coach reviews your interaction skills for the week.',
      25,
      '[{"text":"This week, I practiced...","meaningVi":"tuan nay toi da luyen...","example":"This week, I practiced asking for help."},{"text":"The hardest part was...","meaningVi":"phan kho nhat la...","example":"The hardest part was answering follow-up questions."},{"text":"Next, I need to...","meaningVi":"tiep theo toi can...","example":"Next, I need to speak more naturally."}]'::jsonb,
      '[{"word":"interaction","meaningVi":"tuong tac","example":"Interaction is important in meetings."},{"word":"natural","meaningVi":"tu nhien","example":"I want to sound more natural."},{"word":"review","meaningVi":"on lai","example":"This is my weekly review."}]'::jsonb,
      '["What did you practice this week?","What was the hardest interaction task?","What will you improve next?"]'::jsonb,
      'Act as a speaking coach. Ask the learner to review week two and choose one interaction skill to improve.'
    ),
    (
      '00000000-0000-4000-8000-000000000015'::uuid,
      'workplace-day-15-propose-a-solution',
      15,
      3,
      'B1',
      'workplace',
      'Propose a solution',
      'Suggest a practical solution and explain why it helps.',
      'Your team discusses how to fix a recurring problem.',
      25,
      '[{"text":"One possible solution is...","meaningVi":"mot giai phap co the la...","example":"One possible solution is to add validation earlier."},{"text":"This would help because...","meaningVi":"dieu nay se huu ich vi...","example":"This would help because users get feedback faster."},{"text":"We could start by...","meaningVi":"chung ta co the bat dau bang...","example":"We could start by testing it with one user group."}]'::jsonb,
      '[{"word":"solution","meaningVi":"giai phap","example":"This solution is simple."},{"word":"validate","meaningVi":"kiem tra hop le","example":"We should validate the input."},{"word":"impact","meaningVi":"tac dong","example":"The impact is small but useful."}]'::jsonb,
      '["What solution do you propose?","Why would it help?","How could the team start?"]'::jsonb,
      'Act as a teammate discussing a recurring problem. Ask the learner to propose a solution and defend it briefly.'
    ),
    (
      '00000000-0000-4000-8000-000000000016'::uuid,
      'workplace-day-16-compare-options',
      16,
      3,
      'B1',
      'workplace',
      'Compare options',
      'Compare two options using benefits, risks, and a recommendation.',
      'Your team chooses between two implementation options.',
      25,
      '[{"text":"Option A is better for...","meaningVi":"lua chon A tot hon cho...","example":"Option A is better for speed."},{"text":"The trade-off is...","meaningVi":"su danh doi la...","example":"The trade-off is that it is harder to maintain."},{"text":"I would recommend...","meaningVi":"toi se de xuat...","example":"I would recommend Option B for the first release."}]'::jsonb,
      '[{"word":"trade-off","meaningVi":"su danh doi","example":"There is a trade-off between speed and quality."},{"word":"benefit","meaningVi":"loi ich","example":"The main benefit is lower risk."},{"word":"recommend","meaningVi":"de xuat","example":"I recommend the simpler option."}]'::jsonb,
      '["What are the two options?","What is the trade-off?","Which option do you recommend?"]'::jsonb,
      'Act as a product teammate comparing two options. Ask the learner to explain benefits, risks, and a recommendation.'
    ),
    (
      '00000000-0000-4000-8000-000000000017'::uuid,
      'workplace-day-17-negotiate-priority',
      17,
      3,
      'B1',
      'workplace',
      'Negotiate priority',
      'Discuss priority when there is too much work and limited time.',
      'A manager asks you to take another urgent task.',
      25,
      '[{"text":"I can take this on, but...","meaningVi":"toi co the nhan viec nay nhung...","example":"I can take this on, but the current task will be delayed."},{"text":"Which one should I prioritize?","meaningVi":"toi nen uu tien viec nao","example":"Which one should I prioritize today?"},{"text":"If this is urgent, I can...","meaningVi":"neu viec nay gap, toi co the...","example":"If this is urgent, I can move the bug fix to tomorrow."}]'::jsonb,
      '[{"word":"urgent","meaningVi":"gap","example":"This request is urgent."},{"word":"prioritize","meaningVi":"uu tien","example":"We need to prioritize the release bug."},{"word":"delay","meaningVi":"tri hoan","example":"This may delay the current task."}]'::jsonb,
      '["How do you respond to a new urgent task?","What question can you ask about priority?","What trade-off should you mention?"]'::jsonb,
      'Act as a manager giving the learner a new urgent task. Let the learner negotiate priority politely.'
    ),
    (
      '00000000-0000-4000-8000-000000000018'::uuid,
      'workplace-day-18-disagree-politely',
      18,
      3,
      'B1',
      'workplace',
      'Disagree politely',
      'Disagree with a proposal while keeping the conversation constructive.',
      'A teammate suggests an approach you think is risky.',
      25,
      '[{"text":"I see your point, but...","meaningVi":"toi hieu y ban nhung...","example":"I see your point, but this may create more bugs."},{"text":"My concern is...","meaningVi":"dieu toi lo la...","example":"My concern is that the timeline is too tight."},{"text":"Could we consider...?","meaningVi":"chung ta co the can nhac... khong","example":"Could we consider a smaller first version?"}]'::jsonb,
      '[{"word":"concern","meaningVi":"moi lo","example":"My concern is the release date."},{"word":"constructive","meaningVi":"mang tinh xay dung","example":"Let''s keep the feedback constructive."},{"word":"risky","meaningVi":"rui ro","example":"This approach feels risky."}]'::jsonb,
      '["How do you acknowledge the other person''s point?","What concern do you have?","What alternative can you suggest?"]'::jsonb,
      'Act as a teammate proposing a risky idea. Let the learner disagree politely and suggest an alternative.'
    ),
    (
      '00000000-0000-4000-8000-000000000019'::uuid,
      'workplace-day-19-explain-data',
      19,
      3,
      'B1',
      'workplace',
      'Explain data',
      'Explain a simple metric, what changed, and what it means.',
      'You present a small metric change in a team update.',
      25,
      '[{"text":"The number increased from... to...","meaningVi":"con so tang tu... len...","example":"The number increased from ten to fifteen percent."},{"text":"This suggests that...","meaningVi":"dieu nay cho thay rang...","example":"This suggests that users understand the flow better."},{"text":"We should keep an eye on...","meaningVi":"chung ta nen theo doi...","example":"We should keep an eye on the error rate."}]'::jsonb,
      '[{"word":"metric","meaningVi":"chi so","example":"This metric improved last week."},{"word":"increase","meaningVi":"tang","example":"Signups increased this week."},{"word":"trend","meaningVi":"xu huong","example":"The trend looks positive."}]'::jsonb,
      '["What metric changed?","What does the change suggest?","What should the team monitor next?"]'::jsonb,
      'Act as a team lead asking about a metric. Ask the learner to explain the number, meaning, and next monitoring step.'
    ),
    (
      '00000000-0000-4000-8000-000000000020'::uuid,
      'workplace-day-20-handle-user-issue',
      20,
      3,
      'B1',
      'workplace',
      'Handle a user issue',
      'Explain a user issue and suggest a calm next step.',
      'A support teammate reports that users are stuck.',
      25,
      '[{"text":"Users are having trouble with...","meaningVi":"nguoi dung dang gap kho khan voi...","example":"Users are having trouble with password reset."},{"text":"The issue seems to be...","meaningVi":"van de co ve la...","example":"The issue seems to be an expired link."},{"text":"A good next step is...","meaningVi":"buoc tiep theo tot la...","example":"A good next step is to check the logs."}]'::jsonb,
      '[{"word":"support","meaningVi":"ho tro","example":"The support team reported this issue."},{"word":"stuck","meaningVi":"bi ket","example":"Users are stuck on the login page."},{"word":"logs","meaningVi":"nhat ky he thong","example":"We should check the logs."}]'::jsonb,
      '["What problem are users having?","What does the issue seem to be?","What is a good next step?"]'::jsonb,
      'Act as a support teammate reporting a user issue. Ask the learner to explain the issue and suggest the next step.'
    ),
    (
      '00000000-0000-4000-8000-000000000021'::uuid,
      'workplace-day-21-week-3-review',
      21,
      3,
      'B1',
      'workplace',
      'Week 3 collaboration review',
      'Review solution, priority, disagreement, and data explanation skills.',
      'Your coach asks you to reflect on collaboration conversations.',
      25,
      '[{"text":"I learned to handle...","meaningVi":"toi da hoc cach xu ly...","example":"I learned to handle disagreement more politely."},{"text":"I need more practice with...","meaningVi":"toi can luyen them ve...","example":"I need more practice with explaining data."},{"text":"My next focus is...","meaningVi":"trong tam tiep theo cua toi la...","example":"My next focus is interaction."}]'::jsonb,
      '[{"word":"collaboration","meaningVi":"cong tac","example":"Collaboration requires clear communication."},{"word":"reflect","meaningVi":"nhin lai","example":"I want to reflect on my weak points."},{"word":"focus","meaningVi":"trong tam","example":"My focus is fluency."}]'::jsonb,
      '["What collaboration skill did you practice?","What still feels difficult?","What is your next focus?"]'::jsonb,
      'Act as a speaking coach reviewing week three. Ask the learner to reflect on collaboration and choose a next focus.'
    ),
    (
      '00000000-0000-4000-8000-000000000022'::uuid,
      'workplace-day-22-tell-a-project-story',
      22,
      4,
      'B1',
      'workplace',
      'Tell a project story',
      'Tell a short story about a project using situation, action, and result.',
      'A colleague asks about a project you are proud of.',
      25,
      '[{"text":"The situation was...","meaningVi":"tinh huong la...","example":"The situation was that users could not finish onboarding."},{"text":"What I did was...","meaningVi":"viec toi da lam la...","example":"What I did was simplify the steps."},{"text":"As a result...","meaningVi":"ket qua la...","example":"As a result, more users completed the flow."}]'::jsonb,
      '[{"word":"onboarding","meaningVi":"qua trinh bat dau dung san pham","example":"The onboarding flow was too long."},{"word":"result","meaningVi":"ket qua","example":"The result was positive."},{"word":"proud","meaningVi":"tu hao","example":"I am proud of this project."}]'::jsonb,
      '["What was the situation?","What did you do?","What was the result?"]'::jsonb,
      'Act as a colleague asking about a project. Ask for the situation, action, and result.'
    ),
    (
      '00000000-0000-4000-8000-000000000023'::uuid,
      'workplace-day-23-present-a-recommendation',
      23,
      4,
      'B1',
      'workplace',
      'Present a recommendation',
      'Present a recommendation with reason, risk, and next step.',
      'You recommend a direction in a planning discussion.',
      25,
      '[{"text":"My recommendation is...","meaningVi":"de xuat cua toi la...","example":"My recommendation is to launch a smaller version first."},{"text":"The main risk is...","meaningVi":"rui ro chinh la...","example":"The main risk is that we do not have enough test data."},{"text":"To reduce that risk...","meaningVi":"de giam rui ro do...","example":"To reduce that risk, we can run a small test."}]'::jsonb,
      '[{"word":"direction","meaningVi":"huong di","example":"This direction is safer."},{"word":"launch","meaningVi":"ra mat","example":"We can launch next week."},{"word":"reduce","meaningVi":"giam","example":"This can reduce risk."}]'::jsonb,
      '["What is your recommendation?","What is the main risk?","How can the team reduce that risk?"]'::jsonb,
      'Act as a product manager. Ask the learner to present a recommendation with reason, risk, and next step.'
    ),
    (
      '00000000-0000-4000-8000-000000000024'::uuid,
      'workplace-day-24-handle-questions',
      24,
      4,
      'B1',
      'workplace',
      'Handle questions',
      'Answer challenging questions without freezing or over-explaining.',
      'A teammate challenges your recommendation.',
      25,
      '[{"text":"That''s a fair question.","meaningVi":"do la cau hoi hop ly","example":"That''s a fair question."},{"text":"The short answer is...","meaningVi":"cau tra loi ngan gon la...","example":"The short answer is that it saves time."},{"text":"I can follow up with...","meaningVi":"toi co the bo sung sau ve...","example":"I can follow up with more data after the meeting."}]'::jsonb,
      '[{"word":"challenge","meaningVi":"thach thuc, dat cau hoi kho","example":"He challenged the proposal."},{"word":"short answer","meaningVi":"cau tra loi ngan gon","example":"The short answer is yes."},{"word":"follow up","meaningVi":"bo sung sau","example":"I will follow up with details."}]'::jsonb,
      '["How do you respond to a fair question?","What is the short answer?","What can you follow up with later?"]'::jsonb,
      'Act as a teammate challenging the learner''s idea. Ask two difficult but fair questions.'
    ),
    (
      '00000000-0000-4000-8000-000000000025'::uuid,
      'workplace-day-25-lead-a-short-sync',
      25,
      4,
      'B1',
      'workplace',
      'Lead a short sync',
      'Lead a short meeting with agenda, check-in, and next steps.',
      'You lead a 10-minute team sync.',
      25,
      '[{"text":"Let''s start with...","meaningVi":"hay bat dau voi...","example":"Let''s start with the release status."},{"text":"Can you give a quick update on...?","meaningVi":"ban co the cap nhat nhanh ve... khong","example":"Can you give a quick update on testing?"},{"text":"To wrap up...","meaningVi":"de ket lai...","example":"To wrap up, we have two action items."}]'::jsonb,
      '[{"word":"agenda","meaningVi":"chuong trinh hop","example":"The agenda has three items."},{"word":"sync","meaningVi":"cuoc hop dong bo ngan","example":"We have a sync at 10."},{"word":"wrap up","meaningVi":"ket lai","example":"Let''s wrap up the meeting."}]'::jsonb,
      '["How do you start the sync?","How do you ask for a quick update?","How do you close the meeting?"]'::jsonb,
      'Act as a teammate in a short sync. Let the learner lead the meeting, ask for updates, and close with next steps.'
    ),
    (
      '00000000-0000-4000-8000-000000000026'::uuid,
      'workplace-day-26-give-feedback',
      26,
      4,
      'B1',
      'workplace',
      'Give feedback',
      'Give balanced feedback with one positive point and one improvement.',
      'A teammate asks for feedback on their work.',
      25,
      '[{"text":"What worked well was...","meaningVi":"dieu da lam tot la...","example":"What worked well was the clear layout."},{"text":"One thing to improve is...","meaningVi":"mot diem can cai thien la...","example":"One thing to improve is the error message."},{"text":"A suggestion would be...","meaningVi":"mot goi y la...","example":"A suggestion would be to add an empty state."}]'::jsonb,
      '[{"word":"balanced","meaningVi":"can bang","example":"Balanced feedback is more helpful."},{"word":"improve","meaningVi":"cai thien","example":"This section can improve."},{"word":"suggestion","meaningVi":"goi y","example":"I have one suggestion."}]'::jsonb,
      '["What worked well?","What can be improved?","What suggestion can you give?"]'::jsonb,
      'Act as a teammate asking for feedback. Let the learner give one positive point and one improvement suggestion.'
    ),
    (
      '00000000-0000-4000-8000-000000000027'::uuid,
      'workplace-day-27-recap-action-items',
      27,
      4,
      'B1',
      'workplace',
      'Recap action items',
      'Recap who will do what, by when, and what depends on what.',
      'At the end of a meeting, you summarize the action items.',
      25,
      '[{"text":"I''ll take care of...","meaningVi":"toi se phu trach...","example":"I''ll take care of the API test."},{"text":"You will handle...","meaningVi":"ban se xu ly...","example":"You will handle the design update."},{"text":"This depends on...","meaningVi":"viec nay phu thuoc vao...","example":"This depends on getting test data today."}]'::jsonb,
      '[{"word":"action item","meaningVi":"viec can lam","example":"We have three action items."},{"word":"owner","meaningVi":"nguoi phu trach","example":"Each task needs an owner."},{"word":"dependency","meaningVi":"phu thuoc","example":"This dependency may block us."}]'::jsonb,
      '["What will you take care of?","What will the teammate handle?","What does the task depend on?"]'::jsonb,
      'Act as a teammate at the end of a meeting. Ask the learner to recap action items, owners, and dependencies.'
    ),
    (
      '00000000-0000-4000-8000-000000000028'::uuid,
      'workplace-day-28-week-4-review',
      28,
      4,
      'B1',
      'workplace',
      'Week 4 confident speaking review',
      'Review confident speaking skills and choose one area to polish.',
      'Your speaking coach reviews your confident speaking week.',
      25,
      '[{"text":"I can now...","meaningVi":"bay gio toi co the...","example":"I can now give a recommendation more clearly."},{"text":"I sound more confident when...","meaningVi":"toi nghe tu tin hon khi...","example":"I sound more confident when I use clear structure."},{"text":"I want to polish...","meaningVi":"toi muon trau chuot...","example":"I want to polish my Q&A answers."}]'::jsonb,
      '[{"word":"polish","meaningVi":"trau chuot","example":"I want to polish my opening line."},{"word":"structure","meaningVi":"cau truc","example":"A clear structure helps fluency."},{"word":"confident","meaningVi":"tu tin","example":"I sound more confident now."}]'::jsonb,
      '["What can you do now?","When do you sound more confident?","What do you want to polish?"]'::jsonb,
      'Act as a speaking coach. Ask the learner to review confident speaking skills and choose one area to polish.'
    ),
    (
      '00000000-0000-4000-8000-000000000029'::uuid,
      'workplace-day-29-mock-workplace-conversation',
      29,
      5,
      'B1',
      'workplace',
      'Mock workplace conversation',
      'Handle a mixed workplace conversation using update, clarification, opinion, and next steps.',
      'A manager asks about a project, a blocker, your opinion, and next steps.',
      30,
      '[{"text":"To give you the full picture...","meaningVi":"de cho ban buc tranh day du...","example":"To give you the full picture, the feature works but tests are not done."},{"text":"The key point is...","meaningVi":"diem chinh la...","example":"The key point is that we need one more review."},{"text":"My next step is...","meaningVi":"buoc tiep theo cua toi la...","example":"My next step is to fix the last bug."}]'::jsonb,
      '[{"word":"full picture","meaningVi":"buc tranh day du","example":"Let me give the full picture."},{"word":"key point","meaningVi":"diem chinh","example":"The key point is the timeline."},{"word":"mixed","meaningVi":"ket hop","example":"This is a mixed conversation."}]'::jsonb,
      '["What is the full picture?","What is the key point?","What is your next step?"]'::jsonb,
      'Act as a manager in a mixed workplace conversation. Ask about status, blocker, opinion, and next step.'
    ),
    (
      '00000000-0000-4000-8000-000000000030'::uuid,
      'workplace-day-30-final-mini-assessment',
      30,
      5,
      'B1',
      'workplace',
      'Final mini assessment',
      'Give a longer workplace answer that combines introduction, progress, problem, opinion, and plan.',
      'Your coach runs a final 30-day workplace speaking assessment.',
      30,
      '[{"text":"Over the last month, I have improved...","meaningVi":"trong thang qua toi da cai thien...","example":"Over the last month, I have improved my meeting answers."},{"text":"I can handle...","meaningVi":"toi co the xu ly...","example":"I can handle status updates and clarification questions."},{"text":"My next goal is...","meaningVi":"muc tieu tiep theo cua toi la...","example":"My next goal is to speak more naturally in real meetings."}]'::jsonb,
      '[{"word":"assessment","meaningVi":"danh gia","example":"This is my final assessment."},{"word":"handle","meaningVi":"xu ly","example":"I can handle follow-up questions."},{"word":"next goal","meaningVi":"muc tieu tiep theo","example":"My next goal is fluency."}]'::jsonb,
      '["What have you improved over the last month?","What workplace conversations can you handle now?","What is your next speaking goal?"]'::jsonb,
      'Act as a speaking coach running a final assessment. Ask the learner to give a longer answer about progress, confidence, and next goal.'
    )
),
rubric as (
  select
    '[{"key":"taskCompletion","label":"Task completion","guidance":"Did the learner answer the mission goal clearly enough?"},{"key":"fluency","label":"Fluency","guidance":"Did the answer connect ideas without stopping too early?"},{"key":"accuracy","label":"Accuracy","guidance":"Did the learner use correct sentence structure and collocations?"},{"key":"vocabulary","label":"Vocabulary","guidance":"Did the learner use the target chunks and useful workplace words?"},{"key":"interaction","label":"Interaction","guidance":"Did the learner ask, clarify, confirm, or extend the conversation?"}]'::jsonb as rubric_json
)
insert into public.missions (
  id,
  slug,
  day_number,
  week_number,
  level,
  track,
  title,
  goal,
  scenario,
  estimated_minutes,
  target_chunks,
  target_vocabulary,
  practice_questions,
  roleplay_prompt,
  rubric_json
)
select
  mission_seed.id,
  mission_seed.slug,
  mission_seed.day_number,
  mission_seed.week_number,
  mission_seed.level,
  mission_seed.track,
  mission_seed.title,
  mission_seed.goal,
  mission_seed.scenario,
  mission_seed.estimated_minutes,
  mission_seed.target_chunks,
  mission_seed.target_vocabulary,
  mission_seed.practice_questions,
  mission_seed.roleplay_prompt,
  rubric.rubric_json
from mission_seed
cross join rubric
on conflict (slug) do update set
  day_number = excluded.day_number,
  week_number = excluded.week_number,
  level = excluded.level,
  track = excluded.track,
  title = excluded.title,
  goal = excluded.goal,
  scenario = excluded.scenario,
  estimated_minutes = excluded.estimated_minutes,
  target_chunks = excluded.target_chunks,
  target_vocabulary = excluded.target_vocabulary,
  practice_questions = excluded.practice_questions,
  roleplay_prompt = excluded.roleplay_prompt,
  rubric_json = excluded.rubric_json,
  updated_at = now();
