with mission_seed (
  id,
  slug,
  day_number,
  week_number,
  level,
  track,
  title,
  goal,
  scenario,
  estimated_minutes,
  target_chunks,
  target_vocabulary,
  practice_questions,
  roleplay_prompt
) as (
  values
    (
      '00000000-0000-4000-8000-000000000001'::uuid,
      'workplace-day-01-introduce-yourself',
      1,
      1,
      'A2',
      'workplace',
      'Introduce yourself',
      'Introduce who you are, what you do, and one thing you are working on.',
      'You meet a new teammate on their first day.',
      20,
      '[{"text":"I''m responsible for...","meaningVi":"toi phu trach...","example":"I''m responsible for building the dashboard."},{"text":"I mainly work on...","meaningVi":"toi chu yeu lam ve...","example":"I mainly work on backend features."},{"text":"Right now, I''m focusing on...","meaningVi":"hien tai toi dang tap trung vao...","example":"Right now, I''m focusing on fixing login issues."}]'::jsonb,
      '[{"word":"responsible","meaningVi":"phu trach","example":"I''m responsible for testing the new feature."},{"word":"feature","meaningVi":"tinh nang","example":"This feature helps users track progress."},{"word":"team","meaningVi":"doi nhom","example":"I work with a small product team."}]'::jsonb,
      '["What is your role?","What do you mainly work on?","What are you focusing on right now?"]'::jsonb,
      'Act as a friendly new teammate. Ask the learner to introduce themself, then ask one follow-up question about their current work.'
    ),
    (
      '00000000-0000-4000-8000-000000000002'::uuid,
      'workplace-day-02-describe-your-job',
      2,
      1,
      'A2',
      'workplace',
      'Describe your job',
      'Describe your job responsibilities in simple, clear English.',
      'A non-technical colleague asks what your job is like.',
      20,
      '[{"text":"My role involves...","meaningVi":"vai tro cua toi bao gom...","example":"My role involves writing code and reviewing pull requests."},{"text":"I usually...","meaningVi":"toi thuong...","example":"I usually check requirements before I start coding."},{"text":"I work closely with...","meaningVi":"toi lam viec chat che voi...","example":"I work closely with designers and product managers."}]'::jsonb,
      '[{"word":"requirement","meaningVi":"yeu cau","example":"I need to understand the requirement first."},{"word":"review","meaningVi":"xem lai, danh gia","example":"I review code before it is merged."},{"word":"collaborate","meaningVi":"cong tac","example":"I collaborate with the design team."}]'::jsonb,
      '["What does your role involve?","Who do you work closely with?","What do you usually do before starting a task?"]'::jsonb,
      'Act as a non-technical colleague. Ask the learner to explain their job in plain English, then ask for one concrete example.'
    ),
    (
      '00000000-0000-4000-8000-000000000003'::uuid,
      'workplace-day-03-talk-about-routine',
      3,
      1,
      'A2',
      'workplace',
      'Talk about your routine',
      'Talk about your daily work routine using simple sequence words.',
      'You have small talk with a coworker about a normal workday.',
      20,
      '[{"text":"Every day, I...","meaningVi":"moi ngay toi...","example":"Every day, I check my tasks and messages."},{"text":"I usually start by...","meaningVi":"toi thuong bat dau bang viec...","example":"I usually start by reviewing priorities."},{"text":"After that, I...","meaningVi":"sau do toi...","example":"After that, I join the daily meeting."}]'::jsonb,
      '[{"word":"routine","meaningVi":"thoi quen hang ngay","example":"My morning routine is simple."},{"word":"priority","meaningVi":"uu tien","example":"I check my top priority first."},{"word":"standup","meaningVi":"cuoc hop ngan hang ngay","example":"We have a standup every morning."}]'::jsonb,
      '["How do you usually start your workday?","What do you do after your daily meeting?","What is one important part of your routine?"]'::jsonb,
      'Act as a coworker making small talk. Ask about the learner''s workday routine and respond naturally with one follow-up question.'
    ),
    (
      '00000000-0000-4000-8000-000000000004'::uuid,
      'workplace-day-04-ask-for-clarification',
      4,
      1,
      'A2',
      'workplace',
      'Ask for clarification',
      'Ask polite clarification questions when a request is unclear.',
      'A teammate gives you an unclear task requirement.',
      20,
      '[{"text":"Could you clarify...?","meaningVi":"ban co the lam ro...?","example":"Could you clarify the expected result?"},{"text":"Do you mean...?","meaningVi":"y ban la...?","example":"Do you mean the mobile layout or desktop layout?"},{"text":"Just to confirm...","meaningVi":"de xac nhan lai...","example":"Just to confirm, this should be done by Friday, right?"}]'::jsonb,
      '[{"word":"clarify","meaningVi":"lam ro","example":"Could you clarify the requirement?"},{"word":"expected","meaningVi":"duoc mong doi","example":"What is the expected behavior?"},{"word":"confirm","meaningVi":"xac nhan","example":"I want to confirm the deadline."}]'::jsonb,
      '["What can you say when a requirement is unclear?","How do you confirm a deadline?","How do you ask about the expected result?"]'::jsonb,
      'Act as a teammate giving a vague task. Let the learner ask clarification questions, then answer briefly.'
    ),
    (
      '00000000-0000-4000-8000-000000000005'::uuid,
      'workplace-day-05-explain-a-problem',
      5,
      1,
      'A2',
      'workplace',
      'Explain a problem',
      'Explain a blocker or problem clearly and ask for help.',
      'You report a blocker during a daily standup.',
      20,
      '[{"text":"The main issue is...","meaningVi":"van de chinh la...","example":"The main issue is that the API returns an error."},{"text":"I''m blocked by...","meaningVi":"toi dang bi chan boi...","example":"I''m blocked by missing test data."},{"text":"I need help with...","meaningVi":"toi can ho tro ve...","example":"I need help with reproducing the bug."}]'::jsonb,
      '[{"word":"blocker","meaningVi":"tro ngai dang chan tien do","example":"The missing API key is a blocker."},{"word":"issue","meaningVi":"van de","example":"There is an issue with the login page."},{"word":"reproduce","meaningVi":"tai hien loi","example":"I cannot reproduce the bug locally."}]'::jsonb,
      '["What is the main issue?","What are you blocked by?","What help do you need?"]'::jsonb,
      'Act as a team lead in a daily standup. Ask what the learner worked on, what the blocker is, and what help they need.'
    ),
    (
      '00000000-0000-4000-8000-000000000006'::uuid,
      'workplace-day-06-give-an-opinion',
      6,
      1,
      'A2',
      'workplace',
      'Give an opinion',
      'Give a short workplace opinion and support it with one reason.',
      'Your team discusses a product or technical decision.',
      20,
      '[{"text":"I think we should...","meaningVi":"toi nghi chung ta nen...","example":"I think we should keep the first version simple."},{"text":"In my opinion...","meaningVi":"theo y kien cua toi...","example":"In my opinion, this option is easier to maintain."},{"text":"The main reason is...","meaningVi":"ly do chinh la...","example":"The main reason is that it reduces risk."}]'::jsonb,
      '[{"word":"option","meaningVi":"lua chon","example":"This option is faster to build."},{"word":"maintain","meaningVi":"bao tri","example":"This code is easier to maintain."},{"word":"risk","meaningVi":"rui ro","example":"We should reduce risk in the first release."}]'::jsonb,
      '["What option do you prefer?","Why do you think that option is better?","What is one risk we should avoid?"]'::jsonb,
      'Act as a product teammate. Ask the learner for their opinion about keeping a feature simple or adding more options.'
    ),
    (
      '00000000-0000-4000-8000-000000000007'::uuid,
      'workplace-day-07-review-and-mini-assessment',
      7,
      1,
      'A2',
      'workplace',
      'Review and mini assessment',
      'Review the week and give a longer answer about your work, routine, and challenges.',
      'Your coach asks you to summarize what you learned this week.',
      25,
      '[{"text":"This week, I learned how to...","meaningVi":"tuan nay toi da hoc cach...","example":"This week, I learned how to explain blockers."},{"text":"I still need to improve...","meaningVi":"toi van can cai thien...","example":"I still need to improve my fluency."},{"text":"Next week, I want to...","meaningVi":"tuan toi toi muon...","example":"Next week, I want to speak with more confidence."}]'::jsonb,
      '[{"word":"improve","meaningVi":"cai thien","example":"I want to improve my speaking speed."},{"word":"confidence","meaningVi":"su tu tin","example":"I need more confidence in meetings."},{"word":"progress","meaningVi":"tien bo","example":"I can see some progress this week."}]'::jsonb,
      '["What did you learn this week?","What was difficult for you?","What do you want to improve next week?"]'::jsonb,
      'Act as a supportive speaking coach. Ask the learner to review their week, mention one strength, and choose one area to improve.'
    )
),
rubric as (
  select
    '[
      {"key":"taskCompletion","label":"Task completion","guidance":"Did the learner answer the mission goal clearly enough?"},
      {"key":"fluency","label":"Fluency","guidance":"Did the answer connect ideas without stopping too early?"},
      {"key":"accuracy","label":"Accuracy","guidance":"Did the learner use correct sentence structure and collocations?"},
      {"key":"vocabulary","label":"Vocabulary","guidance":"Did the learner use the target chunks and useful workplace words?"},
      {"key":"interaction","label":"Interaction","guidance":"Did the learner ask, clarify, confirm, or extend the conversation?"}
    ]'::jsonb as rubric_json
)
insert into public.missions (
  id,
  slug,
  day_number,
  week_number,
  level,
  track,
  title,
  goal,
  scenario,
  estimated_minutes,
  target_chunks,
  target_vocabulary,
  practice_questions,
  roleplay_prompt,
  rubric_json
)
select
  mission_seed.id,
  mission_seed.slug,
  mission_seed.day_number,
  mission_seed.week_number,
  mission_seed.level,
  mission_seed.track,
  mission_seed.title,
  mission_seed.goal,
  mission_seed.scenario,
  mission_seed.estimated_minutes,
  mission_seed.target_chunks,
  mission_seed.target_vocabulary,
  mission_seed.practice_questions,
  mission_seed.roleplay_prompt,
  rubric.rubric_json
from mission_seed
cross join rubric
on conflict (slug) do update set
  day_number = excluded.day_number,
  week_number = excluded.week_number,
  level = excluded.level,
  track = excluded.track,
  title = excluded.title,
  goal = excluded.goal,
  scenario = excluded.scenario,
  estimated_minutes = excluded.estimated_minutes,
  target_chunks = excluded.target_chunks,
  target_vocabulary = excluded.target_vocabulary,
  practice_questions = excluded.practice_questions,
  roleplay_prompt = excluded.roleplay_prompt,
  rubric_json = excluded.rubric_json,
  updated_at = now();
